# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f17e30ec82e883d52a68ed33f603c597164f9b745ee93db6e546bdfb0f0cb65e58fb309062930509bd5288dce132da9ffce9729e2f9c76d657700eeb7dc560ed

test:
  secret_key_base: 70d08978e2eb624bb4412d8f254c3eaed6caabb65992492e20e56ddf616c7ae29e286a6680d54f516962481952ebc0143a451335d9fe6ddab4a355febf5189eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
